[tool.poetry]
name = "certmonitor"
version = "0.1.0"
description = "A simple package to parse web certificates"
authors = ["Brad Haas <bradh11@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.2"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
