// rust_certinfo/src/der/oid.rs
//
// OBJECT IDENTIFIER decoder. DER OIDs are a sequence of base-128 arcs:
// each arc's bytes have the high bit set on every byte except the last.
// The first byte combines the first two arcs as `40*X + Y` where X is
// 0, 1, or 2.
//
// We never emit OIDs back to DER — only decode them — so this module is
// decode-only and lives entirely on borrowed slices.

use crate::error::ParseError;

/// A borrowed reference to OID body bytes (the value field of an OID TLV,
/// not including the 0x06 tag or the length prefix).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Oid<'a>(&'a [u8]);

impl<'a> Oid<'a> {
    /// Wrap the raw OID body bytes. Validates that the bytes are well-formed.
    pub fn from_bytes(bytes: &'a [u8]) -> Result<Self, ParseError> {
        if bytes.is_empty() {
            return Err(ParseError::InvalidOid);
        }
        // Validate continuation bit form: every byte except the terminator
        // of an arc must have the high bit set; the byte AFTER a terminator
        // is the start of the next arc.
        let mut i = 0;
        while i < bytes.len() {
            // Walk one arc.
            let arc_start = i;
            while i < bytes.len() && bytes[i] & 0x80 != 0 {
                i += 1;
            }
            if i >= bytes.len() {
                return Err(ParseError::InvalidOid);
            }
            // i now points at the terminator byte.
            // Reject leading-zero continuation byte (non-canonical).
            if i > arc_start && bytes[arc_start] == 0x80 {
                return Err(ParseError::InvalidOid);
            }
            i += 1;
        }
        Ok(Self(bytes))
    }

    pub fn as_bytes(&self) -> &'a [u8] {
        self.0
    }

    /// Render as dotted decimal, e.g. `1.2.840.113549.1.1.11`.
    pub fn to_id_string(self) -> String {
        let mut out = String::with_capacity(self.0.len() * 2);
        let mut bytes = self.0.iter().copied();

        // First byte combines arc 1 and arc 2.
        let first = match bytes.next() {
            Some(b) => b,
            None => return out,
        };
        let arc1 = (first / 40).min(2) as u64;
        let arc2 = (first as u64) - 40 * arc1;
        out.push_str(&arc1.to_string());
        out.push('.');
        out.push_str(&arc2.to_string());

        let mut value: u64 = 0;
        for b in bytes {
            // Multiply existing value by 128 (left shift by 7).
            let shifted = match value.checked_shl(7) {
                Some(v) => v,
                None => {
                    // Saturate gracefully: this is a parser, not a critical
                    // crypto path — at worst the OID renders truncated, but
                    // we already validated the bytes in `from_bytes`.
                    return out;
                }
            };
            value = shifted | (b as u64 & 0x7f);
            if b & 0x80 == 0 {
                out.push('.');
                out.push_str(&value.to_string());
                value = 0;
            }
        }
        out
    }
}

// ---- Well-known OIDs as raw DER body bytes ---------------------------------
// Encoded as the value bytes only (no tag, no length). Generated by hand
// from the dotted-decimal forms; verified by the round-trip tests below.

/// 1.2.840.113549.1.1.1 — rsaEncryption
pub const OID_RSA_ENCRYPTION: &[u8] = &[0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01];

/// 1.2.840.10045.2.1 — id-ecPublicKey
pub const OID_EC_PUBLIC_KEY: &[u8] = &[0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01];

// Curve OIDs (RFC 5480, RFC 5639). Used to map curve OID → field bit length.
/// 1.2.840.10045.3.1.7 — secp256r1 / P-256 / prime256v1
pub const OID_SECP256R1: &[u8] = &[0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07];
/// 1.3.132.0.34 — secp384r1 / P-384
pub const OID_SECP384R1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x22];
/// 1.3.132.0.35 — secp521r1 / P-521
pub const OID_SECP521R1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x23];
/// 1.3.132.0.10 — secp256k1 (Bitcoin curve, occasionally seen in self-signed certs)
pub const OID_SECP256K1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x0a];

// Extension OIDs (RFC 5280)
/// 2.5.29.14 — id-ce-subjectKeyIdentifier
pub const OID_EXT_SKI: &[u8] = &[0x55, 0x1d, 0x0e];
/// 2.5.29.19 — id-ce-basicConstraints
pub const OID_EXT_BASIC_CONSTRAINTS: &[u8] = &[0x55, 0x1d, 0x13];
/// 2.5.29.35 — id-ce-authorityKeyIdentifier
pub const OID_EXT_AKI: &[u8] = &[0x55, 0x1d, 0x23];

// Attribute Type OIDs for Name parsing (RFC 5280 §4.1.2.4)
/// 2.5.4.3 — id-at-commonName
pub const OID_AT_COMMON_NAME: &[u8] = &[0x55, 0x04, 0x03];
/// 2.5.4.6 — id-at-countryName
pub const OID_AT_COUNTRY_NAME: &[u8] = &[0x55, 0x04, 0x06];
/// 2.5.4.10 — id-at-organizationName
pub const OID_AT_ORGANIZATION_NAME: &[u8] = &[0x55, 0x04, 0x0a];
/// 2.5.4.11 — id-at-organizationalUnitName
pub const OID_AT_ORGANIZATIONAL_UNIT_NAME: &[u8] = &[0x55, 0x04, 0x0b];

// ---- Post-quantum signature/key algorithm OIDs ------------------------------
//
// Contributor-facing data table: adding a new PQ algorithm is one entry
// here plus nothing else — `x509::spki` and the chain analysis pick it up
// automatically. Every entry is verified by the `pq_table_*` tests below
// (byte encoding round-trips to the dotted form, no duplicates).
//
// Sources (every OID below is copy-checkable against these):
//
//   - NIST CSOR algorithm registry (the authority for the sigAlgs arc
//     2.16.840.1.101.3.4.3 used by ML-DSA and SLH-DSA):
//     https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration
//   - ML-DSA (FIPS 204, https://csrc.nist.gov/pubs/fips/204/final):
//     X.509 algorithm identifiers per RFC 9881 §3
//     (https://www.rfc-editor.org/rfc/rfc9881.html) — sigAlgs .17/.18/.19.
//   - SLH-DSA (FIPS 205, https://csrc.nist.gov/pubs/fips/205/final):
//     X.509 algorithm identifiers per RFC 9909
//     (https://www.rfc-editor.org/rfc/rfc9909.html) — sigAlgs .20–.31,
//     ordered sha2-128s/f, 192s/f, 256s/f, then shake-128s/f, 192s/f, 256s/f.
//   - Composite ML-DSA: draft-ietf-lamps-pq-composite-sigs-19
//     (https://datatracker.ietf.org/doc/draft-ietf-lamps-pq-composite-sigs/19/),
//     name→OID table maintained at
//     https://github.com/lamps-wg/draft-composite-sigs/blob/main/src/algParams.md
//     — IANA-assigned PKIX arc 1.3.6.1.5.5.7.6.37–.54. NOTE: drafts ≤ -12
//     used Entrust's prototyping arc 2.16.840.1.114027.80.8.1; those
//     codepoints were abandoned and are intentionally NOT listed. If the
//     draft renumbers again before RFC, this block is the only place to
//     update.
//   - Falcon / FN-DSA (future FIPS 206): no stable OID codepoints as of
//     June 2026. TODO: add once NIST CSOR assigns them.
//
// These OIDs identify both the SubjectPublicKeyInfo algorithm and the
// certificate signatureAlgorithm — ML-DSA/SLH-DSA use the same OID for
// the key and the signature, with absent parameters.
//
// Adding an entry takes exactly the two things the registries publish —
// the dotted-decimal OID and the algorithm name:
//
//     PqAlgorithm::standalone("2.16.840.1.101.3.4.3.17", "ml-dsa-44"),
//
// (use `::composite(...)` for hybrid composite algorithms). Certificates
// carry OIDs DER-encoded (X.690 §8.19) and the parser matches those raw
// bytes, but that encoding is derived from the dotted string AT COMPILE
// TIME by `encode_dotted` below — never written by hand. A malformed
// dotted string fails the build, and the `pq_table_*` test round-trips
// every derived encoding through the independent runtime decoder.

/// One post-quantum algorithm the parser recognizes.
///
/// Construct with [`PqAlgorithm::standalone`] or
/// [`PqAlgorithm::composite`]; the DER byte encoding is derived from
/// `dotted` at compile time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PqAlgorithm {
    /// Dotted-decimal form as published in the source registry.
    pub dotted: &'static str,
    /// Python-facing lowercase name (the `algorithm` dict field).
    pub name: &'static str,
    /// True for hybrid composite signatures (PQ + classical in one OID).
    pub composite: bool,
    oid_bytes: [u8; MAX_OID_LEN],
    oid_len: usize,
}

/// Generous upper bound for an encoded OID (every entry today is ≤ 9
/// bytes; the const assert in `encode_dotted` catches overflow).
const MAX_OID_LEN: usize = 24;

impl PqAlgorithm {
    /// OID body bytes (value field only, no tag/length), derived from
    /// `dotted` at construction.
    pub fn oid(&self) -> &[u8] {
        &self.oid_bytes[..self.oid_len]
    }

    /// A standalone PQ algorithm (ML-DSA, SLH-DSA, ...).
    const fn standalone(dotted: &'static str, name: &'static str) -> Self {
        Self::new(dotted, name, false)
    }

    /// A hybrid composite algorithm (PQ + classical under one OID).
    const fn composite(dotted: &'static str, name: &'static str) -> Self {
        Self::new(dotted, name, true)
    }

    const fn new(dotted: &'static str, name: &'static str, composite: bool) -> Self {
        let (oid_bytes, oid_len) = encode_dotted(dotted);
        Self {
            dotted,
            name,
            composite,
            oid_bytes,
            oid_len,
        }
    }
}

/// DER-encode a dotted-decimal OID at compile time (X.690 §8.19): the
/// first byte combines the first two arcs as `40 × arc1 + arc2` (`2.16`
/// → 0x60, `1.3` → 0x2b); every later arc is base-128, big-endian, with
/// the high bit set on every byte except its last (`840` → `0x86 0x48`;
/// arcs under 128 are one literal byte, `17` → `0x11`).
///
/// Runs in const context, so a malformed dotted string is a build error
/// rather than a runtime surprise.
const fn encode_dotted(dotted: &str) -> ([u8; MAX_OID_LEN], usize) {
    let bytes = dotted.as_bytes();
    let mut out = [0u8; MAX_OID_LEN];
    let mut out_len = 0;
    let mut arcs_done = 0u32;
    let mut first_arc = 0u64;
    let mut value = 0u64;
    let mut has_digit = false;
    let mut i = 0;
    // One extra iteration with a virtual trailing '.' flushes the last arc.
    while i <= bytes.len() {
        let c = if i == bytes.len() { b'.' } else { bytes[i] };
        if c == b'.' {
            assert!(has_digit, "empty arc in dotted OID");
            if arcs_done == 0 {
                assert!(value <= 2, "first OID arc must be 0, 1, or 2");
                first_arc = value;
            } else if arcs_done == 1 {
                let combined = first_arc * 40 + value;
                assert!(
                    combined < 0x80,
                    "second OID arc too large for the single-byte form"
                );
                out[0] = combined as u8;
                out_len = 1;
            } else {
                // Base-128: most significant 7-bit group first,
                // continuation bit on all bytes except the last.
                let mut n = 1;
                let mut tmp = value;
                while tmp >= 0x80 {
                    tmp >>= 7;
                    n += 1;
                }
                assert!(out_len + n <= MAX_OID_LEN, "OID longer than MAX_OID_LEN");
                let mut k = n;
                let mut v = value;
                while k > 0 {
                    k -= 1;
                    let group = (v & 0x7f) as u8;
                    out[out_len + k] = if k == n - 1 { group } else { group | 0x80 };
                    v >>= 7;
                }
                out_len += n;
            }
            arcs_done += 1;
            value = 0;
            has_digit = false;
        } else {
            assert!(c.is_ascii_digit(), "non-digit character in dotted OID");
            value = value * 10 + (c - b'0') as u64;
            has_digit = true;
        }
        i += 1;
    }
    assert!(arcs_done >= 2, "dotted OID needs at least two arcs");
    (out, out_len)
}

pub const PQ_ALGORITHMS: &[PqAlgorithm] = &[
    // ML-DSA (FIPS 204) — RFC 9881 §3: https://www.rfc-editor.org/rfc/rfc9881.html
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.17", "ml-dsa-44"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.18", "ml-dsa-65"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.19", "ml-dsa-87"),
    // SLH-DSA (FIPS 205) — all twelve parameter sets, RFC 9909:
    // https://www.rfc-editor.org/rfc/rfc9909.html
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.20", "slh-dsa-sha2-128s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.21", "slh-dsa-sha2-128f"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.22", "slh-dsa-sha2-192s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.23", "slh-dsa-sha2-192f"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.24", "slh-dsa-sha2-256s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.25", "slh-dsa-sha2-256f"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.26", "slh-dsa-shake-128s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.27", "slh-dsa-shake-128f"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.28", "slh-dsa-shake-192s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.29", "slh-dsa-shake-192f"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.30", "slh-dsa-shake-256s"),
    PqAlgorithm::standalone("2.16.840.1.101.3.4.3.31", "slh-dsa-shake-256f"),
    // Composite ML-DSA (draft-ietf-lamps-pq-composite-sigs-19) — name→OID table:
    // https://github.com/lamps-wg/draft-composite-sigs/blob/main/src/algParams.md
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.37", "mldsa44-rsa2048-pss-sha256"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.38", "mldsa44-rsa2048-pkcs15-sha256"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.39", "mldsa44-ed25519-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.40", "mldsa44-ecdsa-p256-sha256"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.41", "mldsa65-rsa3072-pss-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.42", "mldsa65-rsa3072-pkcs15-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.43", "mldsa65-rsa4096-pss-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.44", "mldsa65-rsa4096-pkcs15-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.45", "mldsa65-ecdsa-p256-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.46", "mldsa65-ecdsa-p384-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.47", "mldsa65-ecdsa-brainpoolp256r1-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.48", "mldsa65-ed25519-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.49", "mldsa87-ecdsa-p384-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.50", "mldsa87-ecdsa-brainpoolp384r1-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.51", "mldsa87-ed448-shake256"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.52", "mldsa87-rsa3072-pss-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.53", "mldsa87-rsa4096-pss-sha512"),
    PqAlgorithm::composite("1.3.6.1.5.5.7.6.54", "mldsa87-ecdsa-p521-sha512"),
];

/// Look up a recognized PQ algorithm by OID body bytes.
pub fn pq_algorithm(oid_bytes: &[u8]) -> Option<&'static PqAlgorithm> {
    PQ_ALGORITHMS.iter().find(|alg| alg.oid() == oid_bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roundtrip(bytes: &[u8], expected: &str) {
        let oid = Oid::from_bytes(bytes).unwrap();
        assert_eq!(oid.to_id_string(), expected);
    }

    #[test]
    fn rsa_encryption() {
        roundtrip(OID_RSA_ENCRYPTION, "1.2.840.113549.1.1.1");
    }

    #[test]
    fn ec_public_key() {
        roundtrip(OID_EC_PUBLIC_KEY, "1.2.840.10045.2.1");
    }

    #[test]
    fn secp256r1() {
        roundtrip(OID_SECP256R1, "1.2.840.10045.3.1.7");
    }

    #[test]
    fn secp384r1() {
        roundtrip(OID_SECP384R1, "1.3.132.0.34");
    }

    #[test]
    fn secp521r1() {
        roundtrip(OID_SECP521R1, "1.3.132.0.35");
    }

    #[test]
    fn ski() {
        roundtrip(OID_EXT_SKI, "2.5.29.14");
    }

    #[test]
    fn basic_constraints() {
        roundtrip(OID_EXT_BASIC_CONSTRAINTS, "2.5.29.19");
    }

    #[test]
    fn aki() {
        roundtrip(OID_EXT_AKI, "2.5.29.35");
    }

    #[test]
    fn common_name() {
        roundtrip(OID_AT_COMMON_NAME, "2.5.4.3");
    }

    #[test]
    fn empty_oid_rejected() {
        assert_eq!(Oid::from_bytes(&[]).unwrap_err(), ParseError::InvalidOid);
    }

    #[test]
    fn unterminated_arc_rejected() {
        // Last byte has continuation bit set
        assert_eq!(
            Oid::from_bytes(&[0x2a, 0x86]).unwrap_err(),
            ParseError::InvalidOid
        );
    }

    #[test]
    fn leading_zero_arc_rejected() {
        // 0x80 starts an arc with leading zero — non-canonical.
        assert_eq!(
            Oid::from_bytes(&[0x2a, 0x80, 0x01]).unwrap_err(),
            ParseError::InvalidOid
        );
    }

    #[test]
    fn pq_table_roundtrips_and_has_no_duplicates() {
        use std::collections::HashSet;
        let mut oids: HashSet<&[u8]> = HashSet::new();
        let mut names: HashSet<&str> = HashSet::new();
        for alg in PQ_ALGORITHMS {
            // The compile-time encoder produced alg.oid() from alg.dotted;
            // round-trip through the independent runtime decoder to verify
            // they agree.
            let oid = Oid::from_bytes(alg.oid()).unwrap();
            assert_eq!(
                oid.to_id_string(),
                alg.dotted,
                "derived bytes for {} do not decode back to its dotted form",
                alg.name
            );
            assert!(oids.insert(alg.oid()), "duplicate OID for {}", alg.name);
            assert!(names.insert(alg.name), "duplicate name {}", alg.name);
        }
        // 3 ML-DSA + 12 SLH-DSA + 18 composite ML-DSA
        assert_eq!(PQ_ALGORITHMS.len(), 33);
    }

    #[test]
    fn compile_time_encoder_agrees_with_classic_constants() {
        // Cross-check `encode_dotted` against the long-standing
        // hand-written constants above — an independent fixed point that
        // guards against the encoder and decoder being wrong in
        // compensating ways.
        fn enc(dotted: &str) -> Vec<u8> {
            let (buf, len) = encode_dotted(dotted);
            buf[..len].to_vec()
        }
        assert_eq!(enc("1.2.840.113549.1.1.1"), OID_RSA_ENCRYPTION);
        assert_eq!(enc("1.2.840.10045.2.1"), OID_EC_PUBLIC_KEY);
        assert_eq!(enc("1.3.132.0.34"), OID_SECP384R1);
        assert_eq!(enc("2.5.29.14"), OID_EXT_SKI);
    }

    #[test]
    fn pq_wire_bytes_pinned() {
        // Pin the exact wire bytes for one entry per arc, independent of
        // both the encoder and the decoder, so a shared bug in the two
        // cannot silently shift what the parser matches on.
        let ml_dsa_65 = pq_algorithm(&[0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x12]);
        assert_eq!(ml_dsa_65.unwrap().name, "ml-dsa-65");
        let composite = pq_algorithm(&[0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x25]);
        assert_eq!(composite.unwrap().name, "mldsa44-rsa2048-pss-sha256");
    }

    #[test]
    fn pq_lookup_hits_and_misses() {
        let ml_dsa_65 = &[0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x12];
        assert_eq!(pq_algorithm(ml_dsa_65).unwrap().name, "ml-dsa-65");
        assert!(!pq_algorithm(ml_dsa_65).unwrap().composite);

        let composite = &[0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x06, 0x2d];
        let info = pq_algorithm(composite).unwrap();
        assert_eq!(info.name, "mldsa65-ecdsa-p256-sha512");
        assert!(info.composite);

        assert!(pq_algorithm(OID_RSA_ENCRYPTION).is_none());
        assert!(pq_algorithm(OID_EC_PUBLIC_KEY).is_none());
    }
}
