// rust_certinfo/src/der/oid.rs
//
// OBJECT IDENTIFIER decoder. DER OIDs are a sequence of base-128 arcs:
// each arc's bytes have the high bit set on every byte except the last.
// The first byte combines the first two arcs as `40*X + Y` where X is
// 0, 1, or 2.
//
// We never emit OIDs back to DER — only decode them — so this module is
// decode-only and lives entirely on borrowed slices.

use crate::error::ParseError;

/// A borrowed reference to OID body bytes (the value field of an OID TLV,
/// not including the 0x06 tag or the length prefix).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Oid<'a>(&'a [u8]);

impl<'a> Oid<'a> {
    /// Wrap the raw OID body bytes. Validates that the bytes are well-formed.
    pub fn from_bytes(bytes: &'a [u8]) -> Result<Self, ParseError> {
        if bytes.is_empty() {
            return Err(ParseError::InvalidOid);
        }
        // Validate continuation bit form: every byte except the terminator
        // of an arc must have the high bit set; the byte AFTER a terminator
        // is the start of the next arc.
        let mut i = 0;
        while i < bytes.len() {
            // Walk one arc.
            let arc_start = i;
            while i < bytes.len() && bytes[i] & 0x80 != 0 {
                i += 1;
            }
            if i >= bytes.len() {
                return Err(ParseError::InvalidOid);
            }
            // i now points at the terminator byte.
            // Reject leading-zero continuation byte (non-canonical).
            if i > arc_start && bytes[arc_start] == 0x80 {
                return Err(ParseError::InvalidOid);
            }
            i += 1;
        }
        Ok(Self(bytes))
    }

    pub fn as_bytes(&self) -> &'a [u8] {
        self.0
    }

    /// Render as dotted decimal, e.g. `1.2.840.113549.1.1.11`.
    pub fn to_id_string(self) -> String {
        let mut out = String::with_capacity(self.0.len() * 2);
        let mut bytes = self.0.iter().copied();

        // First byte combines arc 1 and arc 2.
        let first = match bytes.next() {
            Some(b) => b,
            None => return out,
        };
        let arc1 = (first / 40).min(2) as u64;
        let arc2 = (first as u64) - 40 * arc1;
        out.push_str(&arc1.to_string());
        out.push('.');
        out.push_str(&arc2.to_string());

        let mut value: u64 = 0;
        for b in bytes {
            // Multiply existing value by 128 (left shift by 7).
            let shifted = match value.checked_shl(7) {
                Some(v) => v,
                None => {
                    // Saturate gracefully: this is a parser, not a critical
                    // crypto path — at worst the OID renders truncated, but
                    // we already validated the bytes in `from_bytes`.
                    return out;
                }
            };
            value = shifted | (b as u64 & 0x7f);
            if b & 0x80 == 0 {
                out.push('.');
                out.push_str(&value.to_string());
                value = 0;
            }
        }
        out
    }
}

// ---- Well-known OIDs as raw DER body bytes ---------------------------------
// Encoded as the value bytes only (no tag, no length). Generated by hand
// from the dotted-decimal forms; verified by the round-trip tests below.

/// 1.2.840.113549.1.1.1 — rsaEncryption
pub const OID_RSA_ENCRYPTION: &[u8] = &[0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01];

/// 1.2.840.10045.2.1 — id-ecPublicKey
pub const OID_EC_PUBLIC_KEY: &[u8] = &[0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01];

// Curve OIDs (RFC 5480, RFC 5639). Used to map curve OID → field bit length.
/// 1.2.840.10045.3.1.7 — secp256r1 / P-256 / prime256v1
pub const OID_SECP256R1: &[u8] = &[0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07];
/// 1.3.132.0.34 — secp384r1 / P-384
pub const OID_SECP384R1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x22];
/// 1.3.132.0.35 — secp521r1 / P-521
pub const OID_SECP521R1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x23];
/// 1.3.132.0.10 — secp256k1 (Bitcoin curve, occasionally seen in self-signed certs)
pub const OID_SECP256K1: &[u8] = &[0x2b, 0x81, 0x04, 0x00, 0x0a];

// Extension OIDs (RFC 5280)
/// 2.5.29.14 — id-ce-subjectKeyIdentifier
pub const OID_EXT_SKI: &[u8] = &[0x55, 0x1d, 0x0e];
/// 2.5.29.19 — id-ce-basicConstraints
pub const OID_EXT_BASIC_CONSTRAINTS: &[u8] = &[0x55, 0x1d, 0x13];
/// 2.5.29.35 — id-ce-authorityKeyIdentifier
pub const OID_EXT_AKI: &[u8] = &[0x55, 0x1d, 0x23];

// Attribute Type OIDs for Name parsing (RFC 5280 §4.1.2.4)
/// 2.5.4.3 — id-at-commonName
pub const OID_AT_COMMON_NAME: &[u8] = &[0x55, 0x04, 0x03];
/// 2.5.4.6 — id-at-countryName
pub const OID_AT_COUNTRY_NAME: &[u8] = &[0x55, 0x04, 0x06];
/// 2.5.4.10 — id-at-organizationName
pub const OID_AT_ORGANIZATION_NAME: &[u8] = &[0x55, 0x04, 0x0a];
/// 2.5.4.11 — id-at-organizationalUnitName
pub const OID_AT_ORGANIZATIONAL_UNIT_NAME: &[u8] = &[0x55, 0x04, 0x0b];

#[cfg(test)]
mod tests {
    use super::*;

    fn roundtrip(bytes: &[u8], expected: &str) {
        let oid = Oid::from_bytes(bytes).unwrap();
        assert_eq!(oid.to_id_string(), expected);
    }

    #[test]
    fn rsa_encryption() {
        roundtrip(OID_RSA_ENCRYPTION, "1.2.840.113549.1.1.1");
    }

    #[test]
    fn ec_public_key() {
        roundtrip(OID_EC_PUBLIC_KEY, "1.2.840.10045.2.1");
    }

    #[test]
    fn secp256r1() {
        roundtrip(OID_SECP256R1, "1.2.840.10045.3.1.7");
    }

    #[test]
    fn secp384r1() {
        roundtrip(OID_SECP384R1, "1.3.132.0.34");
    }

    #[test]
    fn secp521r1() {
        roundtrip(OID_SECP521R1, "1.3.132.0.35");
    }

    #[test]
    fn ski() {
        roundtrip(OID_EXT_SKI, "2.5.29.14");
    }

    #[test]
    fn basic_constraints() {
        roundtrip(OID_EXT_BASIC_CONSTRAINTS, "2.5.29.19");
    }

    #[test]
    fn aki() {
        roundtrip(OID_EXT_AKI, "2.5.29.35");
    }

    #[test]
    fn common_name() {
        roundtrip(OID_AT_COMMON_NAME, "2.5.4.3");
    }

    #[test]
    fn empty_oid_rejected() {
        assert_eq!(Oid::from_bytes(&[]).unwrap_err(), ParseError::InvalidOid);
    }

    #[test]
    fn unterminated_arc_rejected() {
        // Last byte has continuation bit set
        assert_eq!(
            Oid::from_bytes(&[0x2a, 0x86]).unwrap_err(),
            ParseError::InvalidOid
        );
    }

    #[test]
    fn leading_zero_arc_rejected() {
        // 0x80 starts an arc with leading zero — non-canonical.
        assert_eq!(
            Oid::from_bytes(&[0x2a, 0x80, 0x01]).unwrap_err(),
            ParseError::InvalidOid
        );
    }
}
